# Generated by Django 4.1.4 on 2022-12-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2048, unique=True)),
                ('signature', models.CharField(max_length=2048)),
                ('callback_url', models.CharField(max_length=2048)),
                ('fulfilled', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MadeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('url', models.CharField(max_length=2048)),
            ],
        ),
    ]
