# Generated by Django 4.1.5 on 2023-01-02 15:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptomessage",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
